In [1]:
# ============================================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# ============================================================

# PyTorch para redes neuronales
import torch

# Dataset y DataLoader
from torch.utils.data import Dataset, DataLoader

# Manipulación de datos
import numpy as np
import pandas as pd

# Visualización
from matplotlib import pyplot as plt

# Barra de progreso
from tqdm import tqdm

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [2]:
# ============================================================
# 2. DETECTAR GPU
# ============================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Dispositivo utilizado:", device)

Dispositivo utilizado: cpu

In [3]:
# ============================================================
# 3. CARGAR DATASET
# ============================================================

columnas = [
'A1','A2','A3','A4','A5','A6','A7','A8',
'A9','A10','A11','A12','A13','A14','A15','A16'
]

data = pd.read_csv(
    "crx.data",
    header=None,
    names=columnas
)

print("Dataset cargado correctamente.")
print("Dimensiones:", data.shape)

display(data.head())

Dataset cargado correctamente.
Dimensiones: (690, 16)

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +

In [4]:
# ============================================================
# 4. EXPLORACIÓN INICIAL
# ============================================================

print("Columnas del dataset:")
print(list(data.columns))

print("\nTipos de datos:")
print(data.dtypes)

print("\nValores nulos:")
print(data.isnull().sum())

print("\nCantidad de '?' por columna:")
print((data == '?').sum())

Columnas del dataset:
['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']

Tipos de datos:
A1         str
A2         str
A3     float64
A4         str
A5         str
A6         str
A7         str
A8     float64
A9         str
A10        str
A11      int64
A12        str
A13        str
A14        str
A15      int64
A16        str
dtype: object

Valores nulos:
A1     0
A2     0
A3     0
A4     0
A5     0
A6     0
A7     0
A8     0
A9     0
A10    0
A11    0
A12    0
A13    0
A14    0
A15    0
A16    0
dtype: int64

Cantidad de '?' por columna:
A1     12
A2     12
A3      0
A4      6
A5      6
A6      9
A7      9
A8      0
A9      0
A10     0
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [5]:
# ============================================================
# 5. REEMPLAZAR '?' POR NaN
# ============================================================

data = data.replace('?', np.nan)

print("Valores '?' convertidos a NaN.")

print("\nNulos por columna:")
print(data.isnull().sum())

Valores '?' convertidos a NaN.

Nulos por columna:
A1     12
A2     12
A3      0
A4      6
A5      6
A6      9
A7      9
A8      0
A9      0
A10     0
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [6]:
# ============================================================
# 6. CONVERTIR COLUMNAS NUMÉRICAS
# ============================================================

for col in ['A2','A3','A8','A11','A14','A15']:
    
    data[col] = pd.to_numeric(data[col], errors='coerce')

print("Columnas numéricas convertidas.")

Columnas numéricas convertidas.

In [8]:
# ============================================================
# 7. IMPUTAR VALORES NULOS
# ============================================================

# Columnas numéricas del dataset
numericas = ['A2','A3','A8','A11','A14','A15']

# Columnas categóricas
categoricas = [
'A1','A4','A5','A6','A7',
'A9','A10','A12','A13'
]

# Imputar columnas numéricas con la MEDIA
for col in numericas:

    data[col] = data[col].fillna(data[col].mean())

# Imputar columnas categóricas con la MODA
for col in categoricas:

    data[col] = data[col].fillna(data[col].mode()[0])

print("Valores nulos imputados correctamente.")

print("\nNulos restantes por columna:")
print(data.isnull().sum())

Valores nulos imputados correctamente.

Nulos restantes por columna:
A1     0
A2     0
A3     0
A4     0
A5     0
A6     0
A7     0
A8     0
A9     0
A10    0
A11    0
A12    0
A13    0
A14    0
A15    0
A16    0
dtype: int64

In [9]:
# ============================================================
# 8. CONVERTIR TARGET A BINARIO
# ============================================================

data['A16'] = data['A16'].map({
'+':1,
'-':0
})

print("Distribución de clases:")
print(data['A16'].value_counts())

Distribución de clases:
A16
0    383
1    307
Name: count, dtype: int64

In [10]:
# ============================================================
# 9. SELECCIÓN DE VARIABLES
# ============================================================

features = data.columns[:-1]

target = 'A16'

df = data.copy()

print("Dimensiones del dataset final:", df.shape)

display(df.head())

Dimensiones del dataset final: (690, 16)

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15  A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0    1
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560    1
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824    1
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3    1
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0    1

In [11]:
# ============================================================
# 10. PREPARAR MATRICES X e y
# ============================================================

X = df[features].values

y = df[target].values

print("Forma de X:", X.shape)
print("Forma de y:", y.shape)

Forma de X: (690, 15)
Forma de y: (690,)