In [1]:
# ==========================================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# ==========================================================

# PyTorch
import torch

# Dataset y DataLoader
from torch.utils.data import Dataset, DataLoader

# Manipulación de datos
import numpy as np
import pandas as pd

# Gráficos
from matplotlib import pyplot as plt

# Barra de progreso
from tqdm import tqdm

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [2]:
# ==========================================================
# 2. DETECTAR GPU
# ==========================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Dispositivo utilizado:", device)

Dispositivo utilizado: cpu

In [4]:
# ==========================================================
# 3. CARGAR DATASET
# ==========================================================

data = pd.read_csv(
    "australian.dat",
    header=None,
    sep=r"\s+"
)

print("Dataset cargado correctamente.")

print("Dimensiones del dataset:")
print(data.shape)

print("\nPrimeras filas:")
print(data.head())

Dataset cargado correctamente.
Dimensiones del dataset:
(690, 15)

Primeras filas:
   0      1      2   3   4   5      6   7   8   9   10  11   12    13  14
0   1  22.08  11.46   2   4   4  1.585   0   0   0   1   2  100  1213   0
1   0  22.67   7.00   2   8   4  0.165   0   0   0   0   2  160     1   0
2   0  29.58   1.75   1   4   4  1.250   0   0   0   1   2  280     1   0
3   0  21.67  11.50   1   5   3  0.000   1   1  11   1   2    0     1   1
4   1  20.17   8.17   2   6   4  1.960   1   1  14   0   2   60   159   1

In [5]:
# ==========================================================
# 4. ASIGNAR NOMBRES A COLUMNAS
# ==========================================================

data.columns = [
"A1","A2","A3","A4","A5",
"A6","A7","A8","A9","A10",
"A11","A12","A13","A14",
"A15"
]

print("Columnas asignadas correctamente.")
print(data.columns)

Columnas asignadas correctamente.
Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11',
       'A12', 'A13', 'A14', 'A15'],
      dtype='str')

In [6]:
# ==========================================================
# 5. EXPLORACIÓN INICIAL
# ==========================================================

print("Primeras filas del dataset:")
display(data.head())

print("\nTipos de datos:")
print(data.dtypes)

print("\nEstadísticas básicas:")
display(data.describe())

Primeras filas del dataset:

   A1     A2     A3  A4  A5  A6     A7  A8  A9  A10  A11  A12  A13   A14  A15
0   1  22.08  11.46   2   4   4  1.585   0   0    0    1    2  100  1213    0
1   0  22.67   7.00   2   8   4  0.165   0   0    0    0    2  160     1    0
2   0  29.58   1.75   1   4   4  1.250   0   0    0    1    2  280     1    0
3   0  21.67  11.50   1   5   3  0.000   1   1   11    1    2    0     1    1
4   1  20.17   8.17   2   6   4  1.960   1   1   14    0    2   60   159    1

Tipos de datos:
A1       int64
A2     float64
A3     float64
A4       int64
A5       int64
A6       int64
A7     float64
A8       int64
A9       int64
A10      int64
A11      int64
A12      int64
A13      int64
A14      int64
A15      int64
dtype: object

Estadísticas básicas:

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000,690.000000
mean,0.678261,31.568203,4.758725,1.766667,7.372464,4.692754,2.223406,0.523188,0.427536,2.40000,0.457971,1.928986,184.014493,1018.385507,0.444928
std,0.467482,11.853273,4.978163,0.430063,3.683265,1.992316,3.346513,0.499824,0.495080,4.86294,0.498592,0.298813,172.159274,5210.102598,0.497318
min,0.000000,13.750000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,0.000000,22.670000,1.000000,2.000000,4.000000,4.000000,0.165000,0.000000,0.000000,0.00000,0.000000,2.000000,80.000000,1.000000,0.000000
50%,1.000000,28.625000,2.750000,2.000000,8.000000,4.000000,1.000000,1.000000,0.000000,0.00000,0.000000,2.000000,160.000000,6.000000,0.000000
75%,1.000000,37.707500,7.207500,2.000000,10.000000,5.000000,2.625000,1.000000,1.000000,3.00000,1.000000,2.000000,272.000000,396.500000,1.000000
max,1.000000,80.250000,28.000000,3.000000,14.000000,9.000000,28.500000,1.000000,1.000000,67.00000,1.000000,3.000000,2000.000000,100001.000000,1.000000

In [8]:
# ==========================================================
# 6. CONVERTIR "?" EN NaN
# ==========================================================

data = data.replace("?", np.nan)

print("Valores '?' convertidos a NaN")

print("\nValores nulos por columna:")
print(data.isnull().sum())

Valores '?' convertidos a NaN

Valores nulos por columna:
A1     0
A2     0
A3     0
A4     0
A5     0
A6     0
A7     0
A8     0
A9     0
A10    0
A11    0
A12    0
A13    0
A14    0
A15    0
dtype: int64

In [9]:
# ==========================================================
# 7. CONVERTIR COLUMNAS NUMÉRICAS
# ==========================================================

numeric_cols = ["A2","A3","A8","A11","A14"]

for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors="coerce")

print("Columnas numéricas convertidas.")
print(data.dtypes)

Columnas numéricas convertidas.
A1       int64
A2     float64
A3     float64
A4       int64
A5       int64
A6       int64
A7     float64
A8       int64
A9       int64
A10      int64
A11      int64
A12      int64
A13      int64
A14      int64
A15      int64
dtype: object

In [10]:
# ==========================================================
# 8. IMPUTAR VALORES NULOS
# ==========================================================

for col in data.columns:

    if data[col].dtype == "object":
        data[col] = data[col].fillna(data[col].mode()[0])

    else:
        data[col] = data[col].fillna(data[col].mean())

print("Valores nulos imputados.")

print("\nNulos restantes:")
print(data.isnull().sum())

Valores nulos imputados.

Nulos restantes:
A1     0
A2     0
A3     0
A4     0
A5     0
A6     0
A7     0
A8     0
A9     0
A10    0
A11    0
A12    0
A13    0
A14    0
A15    0
dtype: int64

In [11]:
# ==========================================================
# 9. SEPARAR VARIABLES Y TARGET
# ==========================================================

features = [
"A1","A2","A3","A4","A5",
"A6","A7","A8","A9","A10",
"A11","A12","A13","A14"
]

target = "A15"

X = data[features].values
y = data[target].values

print("Forma de X:", X.shape)
print("Forma de y:", y.shape)

Forma de X: (690, 14)
Forma de y: (690,)

In [13]:
# ==========================================================
# 10. NORMALIZACIÓN
# ==========================================================

def normalizar(X):

    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)

    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma


X_norm, mu, sigma = normalizar(X)

print("Datos normalizados correctamente.")

Datos normalizados correctamente.

In [14]:
# ==========================================================
# 11. TRAIN / TEST SPLIT
# ==========================================================

split = int(len(X_norm) * 0.8)

X_train = X_norm[:split]
y_train = y[:split]

X_test = X_norm[split:]
y_test = y[split:]

print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (552, 14)
Test: (138, 14)