In [1]:
# ============================================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# ============================================================

# PyTorch para redes neuronales
import torch

# Dataset y DataLoader
from torch.utils.data import Dataset, DataLoader

# Manipulación de datos
import numpy as np
import pandas as pd

# Visualización
from matplotlib import pyplot as plt

# Barra de progreso
from tqdm import tqdm

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [2]:
# ============================================================
# 2. DETECTAR GPU
# ============================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Dispositivo utilizado:", device)

Dispositivo utilizado: cpu

In [3]:
# ============================================================
# 3. CARGAR DATASET
# ============================================================

columnas = [
'age','workclass','fnlwgt','education','education-num',
'marital-status','occupation','relationship','race',
'sex','capital-gain','capital-loss','hours-per-week',
'native-country','income'
]

data = pd.read_csv(
    "adult.data",
    header=None,
    names=columnas,
    skipinitialspace=True
)

print("Dataset cargado correctamente.")
print("Dimensiones:", data.shape)

display(data.head())

Dataset cargado correctamente.
Dimensiones: (32561, 15)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
# ============================================================
# 4. EXPLORACIÓN INICIAL
# ============================================================

print("Columnas del dataset:")
print(list(data.columns))

print("\nTipos de datos:")
print(data.dtypes)

print("\nValores nulos:")
print(data.isnull().sum())

print("\nValores '?' por columna:")
print((data == '?').sum())

Columnas del dataset:
['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']

Tipos de datos:
age               int64
workclass           str
fnlwgt            int64
education           str
education-num     int64
marital-status      str
occupation          str
relationship        str
race                str
sex                 str
capital-gain      int64
capital-loss      int64
hours-per-week    int64
native-country      str
income              str
dtype: object

Valores nulos:
age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

Valores '?' por columna:
age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [5]:
# ============================================================
# 5. REEMPLAZAR VALORES '?' POR NaN
# ============================================================

data = data.replace('?', np.nan)

print("Valores '?' convertidos a NaN")

print("\nNulos por columna:")
print(data.isnull().sum())

Valores '?' convertidos a NaN

Nulos por columna:
age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [6]:
# ============================================================
# 6. ELIMINAR COLUMNAS NO NECESARIAS
# ============================================================

data = data.drop(columns=['education','fnlwgt'])

print("Columnas restantes:")
print(list(data.columns))

Columnas restantes:
['age', 'workclass', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']

In [7]:
# ============================================================
# 7. IMPUTAR VALORES NULOS
# ============================================================

for col in ['workclass','occupation','native-country']:

    data[col] = data[col].fillna(data[col].mode()[0])

print("Nulos imputados con moda.")

print("\nNulos restantes:")
print(data.isnull().sum())

Nulos imputados con moda.

Nulos restantes:
age               0
workclass         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [8]:
# ============================================================
# 8. CONVERTIR TARGET A BINARIO
# ============================================================

data['income'] = data['income'].apply(
    lambda x: 1 if x == '>50K' else 0
)

print("Variable objetivo convertida.")
print(data['income'].value_counts())

Variable objetivo convertida.
income
0    24720
1     7841
Name: count, dtype: int64

In [9]:
# ============================================================
# 9. SELECCIÓN DE FEATURES
# ============================================================

features = [
'age',
'workclass',
'education-num',
'marital-status',
'occupation',
'relationship',
'race',
'sex',
'capital-gain',
'capital-loss',
'hours-per-week',
'native-country'
]

target = 'income'

df = data[features + [target]].copy()

print("Dimensiones:", df.shape)

display(df.head())

Dimensiones: (32561, 13)

,age,workclass,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [10]:
# ============================================================
# 10. PREPARAR X e y
# ============================================================

X = df[features].values
y = df[target].values

print("Forma de X:", X.shape)
print("Forma de y:", y.shape)

Forma de X: (32561, 12)
Forma de y: (32561,)